window.projects = [
  {
    id: 0,
    name: "Hamburger Food",
    thumbnail: "assets/images/hamburger-food.png",
    preview: "https://alsiam.github.io/web-design-lab/hamburger-food",
    code: "https://github.com/alsiam/web-design-lab/tree/main/hamburger-food",
  },
  {
    id: 1,
    name: "Bat Ball",
    thumbnail: "assets/images/bat-ball.png",
    preview: "https://alsiam.github.io/web-design-lab/bat-ball",
    code: "https://github.com/alsiam/web-design-lab/tree/main/bat-ball",
  },
  {
    id: 2,
    name: "Cuda Portfolio",
    thumbnail: "assets/images/cuda-portfolio.png",
    preview: "https://alsiam.github.io/web-design-lab/cuda-portfolio",
    code: "https://github.com/alsiam/web-design-lab/tree/main/cuda-portfolio",
  },
  {
    id: 3,
    name: "Dream Theme",
    thumbnail: "assets/images/dream-theme.png",
    preview: "https://alsiam.github.io/web-design-lab/dream-theme",
    code: "https://github.com/alsiam/web-design-lab/tree/main/dream-theme",
  },
  {
    id: 4,
    name: "Facebook Login",
    thumbnail: "assets/images/facebook-login.png",
    preview: "https://alsiam.github.io/web-design-lab/facebook-login",
    code: "https://github.com/alsiam/web-design-lab/tree/main/facebook-login",
  },
  {
    id: 5,
    name: "Fashion Ecommerce",
    thumbnail: "assets/images/fashion-ecommerce.png",
    preview: "https://alsiam.github.io/web-design-lab/fashion-ecommerce",
    code: "https://github.com/alsiam/web-design-lab/tree/main/fashion-ecommerce",
  },
  {
    id: 6,
    name: "Football Club",
    thumbnail: "assets/images/football-club.png",
    preview: "https://alsiam.github.io/web-design-lab/football-club",
    code: "https://github.com/alsiam/web-design-lab/tree/main/football-club",
  },
  {
    id: 7,
    name: "Jamuna News",
    thumbnail: "assets/images/jamuna-news.png",
    preview: "https://alsiam.github.io/web-design-lab/jamuna-news",
    code: "https://github.com/alsiam/web-design-lab/tree/main/jamuna-news",
  },
  {
    id: 8,
    name: "Personal Web",
    thumbnail: "assets/images/personal-web.png",
    preview: "https://alsiam.github.io/web-design-lab/personal-web",
    code: "https://github.com/alsiam/web-design-lab/tree/main/personal-web",
  },
  {
    id: 9,
    name: "Simple Blog",
    thumbnail: "assets/images/simple-blog.png",
    preview: "https://alsiam.github.io/web-design-lab/simple-blog",
    code: "https://github.com/alsiam/web-design-lab/tree/main/simple-blog",
  },
  {
    id: 10,
    name: "Simple Cart",
    thumbnail: "assets/images/shopping-cart.png",
    preview: "https://alsiam.github.io/web-design-lab/simple-cart",
    code: "https://github.com/alsiam/web-design-lab/tree/main/simple-cart",
  },
  {
    id: 11,
    name: "Simple Folio",
    thumbnail: "assets/images/simple-folio.png",
    preview: "https://alsiam.github.io/web-design-lab/simple-folio",
    code: "https://github.com/alsiam/web-design-lab/tree/main/simple-folio",
  },
  {
    id: 12,
    name: "Spourmo Web",
    thumbnail: "assets/images/spourmo-web.png",
    preview: "https://alsiam.github.io/web-design-lab/spourmo-web",
    code: "https://github.com/alsiam/web-design-lab/tree/main/spourmo-web",
  },
  {
    id: 13,
    name: "Systematic Page",
    thumbnail: "assets/images/systematic-page.png",
    preview: "https://alsiam.github.io/web-design-lab/systematic-page",
    code: "https://github.com/alsiam/web-design-lab/tree/main/systematic-page",
  },
  {
    id: 14,
    name: "Bike Palace",
    thumbnail: "assets/images/bike-palace.png",
    preview: "https://alsiam.github.io/web-design-lab/bike-palace",
    code: "https://github.com/alsiam/web-design-lab/tree/main/bike-palace",
  },
];
